#!/usr/bin/python3

class colo:
    HEADER = '\033[95m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    UNDERLINE = '\033[4m'
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'
    BOLD='\033[1;37m'
    YELLOW='\033[1;33m'

import os
path = os.getcwd()

print(colo.CYAN + "IMPORTANT: Make sure you are in the OUTSIDE folder.")
print(colo.BOLD + 'Your cwd is: ' + path)
print(colo.RED + "Are you sure you want to change names? [Y/n]" + colo.NC, end=': ')
inp = input()

if not inp == 'y' and not inp == 'Y':
    exit(0)

for root, dirs, files in os.walk(path):
    basename = os.path.basename(root)
    for file in files:
        if not file.endswith('.cpp'):
            continue
        if not '_' in file:
            continue
        if file.endswith('__Good.cpp'):
            continue
        if file.endswith('__Generator.cpp'):
            continue

        new_file = file
        new_file = new_file.split('_')[0] + '.cpp'
        print('{0}/{1} ===> {0}/{2}'.format(basename, file, new_file))
        os.system('mv {} {}'.format(os.path.join(root, file), os.path.join(root, new_file)))
