#!/usr/bin/python3
class colo:
    HEADER = '\033[95m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    UNDERLINE = '\033[4m'
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'
    BOLD='\033[1;37m'
    YELLOW='\033[1;33m'

import os
import sys

if len(sys.argv) == 1:
    print(colo.RED + "Argument missing." + colo.NC)
    exit(0)

filename = sys.argv[1]
purefilename = ''

if filename.endswith('.cpp'):
    purefilename = filename[:-4]
else:
    purefilename = filename.upper()
    filename = filename + '.cpp'

print("%s[RUNNING: %s]%s" % (colo.CYAN, purefilename, colo.NC))
print("%s[ENTER TEST ID]:%s" % (colo.CYAN, colo.NC), end=' ')
inp = input()

try:
    os.system("echo \">>> input\"; cat in%s" % inp)
    print()
    os.system("echo \">>> output\"; ./{0}.exe < in{1}.txt | tee out{1}.txt".format(purefilename, inp))
    print()
    os.system("echo \">>> answer\"; cat ans%s.txt" % inp)
    print()
    print()
    # os.system("echo diff; diff out{0} ans{0}".format(inp))
    os.system("echo \">>> diff\"; icdiff out{0}.txt ans{0}.txt".format(inp))
    # os.system("echo diff; diff -rqEeB out{0} ans{0} 2> /dev/null".format(inp))
except:
    print("%[FAILED]%s" % (colo.RED, colo.NC))
    exit(0)

print("%s\n[FINISHED]%s" % (colo.GREEN, colo.NC))
