#!/usr/bin/python3
from os import system

def Run(command):
    try:
        system(command)
        print(">>>", command.split('/')[-1])
    except(e):
        print("Failed.")
        print(e)
        exit(1)

HOME = '~'
GIT = HOME + '/Documents/utilities'

## contest_configs
Run('cp ' + HOME + '/.vim/UltiSnips/cpp.snippets'  + ' ' + GIT + '/contest_configs/cpp.snippets')
Run('cp ' + HOME + '/.clang-format'  + ' ' + GIT + '/contest_configs/.clang-format')

# competitive programming tools
Run('cp ' + HOME + '/.local/bin/download_prob.py'  + ' ' + GIT + '/contest_configs/download_prob.py')

## env_configs
Run('cp ' + HOME + '/.env'  + ' ' + GIT + '/env_configs/.env')
Run('cp ' + HOME + '/.bashrc'  + ' ' + GIT + '/env_configs/.bashrc')
Run('cp ' + HOME + '/.vimrc'  + ' ' + GIT + '/env_configs/.vimrc')
Run('cp ' + HOME + '/.config/fish/config.fish'  + ' ' + GIT + '/env_configs/config.fish')
Run('cp ' + HOME + '/.config/alacritty/alacritty.yml'  + ' ' + GIT + '/env_configs/alacritty.yml')
Run('cp ' + HOME + '/.config/ranger/rc.conf'  + ' ' + GIT + '/env_configs/rc.conf')
Run('cp ' + HOME + '/.config/zathura/zathurarc'  + ' ' + GIT + '/env_configs/zathurarc')
Run('cp ' + HOME + '/.vim/plugged/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py'  + ' ' + GIT + '/env_configs/.ycm_extra_conf.py')
Run('cp ' + HOME + '/bg.png'  + ' ' + GIT + '/bg.png')

Run('cp ' + HOME + '/.local/bin/cpToDotfiles'  + ' ' + GIT + '/cpToDotfiles')
