#!/usr/bin/python3
from os import system

def Run(command):
    try:
        system(command)
        print(">>>", command.split('/')[-1])
    except(e):
        print("Failed.")
        print(e)
        exit(1)

HOME = '~'
GIT = HOME + '/Documents/utilities'

## contest_configs
# Run('cp ' + HOME + '/.config/nvim/UltiSnips/cpp.snippets'  + ' ' + GIT + '/contest_configs/cpp.snippets')
Run('cp ' + HOME + '/.config/nvim/coc-settings.json'  + ' ' + GIT + '/env_configs/coc-settings.json')

# competitive programming tools
Run('cp ' + HOME + '/.local/bin/download_prob.py'  + ' ' + GIT + '/contest_configs/download_prob.py')
Run('cp ' + HOME + '/Documents/CP/template.cpp'  + ' ' + GIT + '/contest_configs/template.cpp')

## env_configs
Run('cp ' + HOME + '/.env'  + ' ' + GIT + '/env_configs/.env')
Run('cp ' + HOME + '/.bashrc'  + ' ' + GIT + '/env_configs/.bashrc')
Run('cp ' + HOME + '/.config/nvim/init.vim'  + ' ' + GIT + '/env_configs/init.vim')
Run('cp ' + HOME + '/.config/nvim/ginit.vim'  + ' ' + GIT + '/env_configs/ginit.vim')
Run('cp ' + HOME + '/.tmux.conf'  + ' ' + GIT + '/env_configs/.tmux.conf')
Run('cp ' + HOME + '/.tmux/one'  + ' ' + GIT + '/env_configs/one')
Run('cp ' + HOME + '/.config/fish/config.fish'  + ' ' + GIT + '/env_configs/config.fish')
Run('cp ' + HOME + '/.config/alacritty/alacritty.yml'  + ' ' + GIT + '/env_configs/alacritty.yml')
Run('cp ' + HOME + '/.config/ranger/rc.conf'  + ' ' + GIT + '/env_configs/rc.conf')
# Run('cp ' + HOME + '/.config/zathura/zathurarc'  + ' ' + GIT + '/env_configs/zathurarc')
Run('cp ' + HOME + '/bg.jpg'  + ' ' + GIT + '/bg.jpg')
Run('cp ' + HOME + '/.astylerc'  + ' ' + GIT + '/env_configs/.astylerc')

Run('cp ' + HOME + '/.local/bin/cpToDotfiles'  + ' ' + GIT + '/cpToDotfiles')
