#!/usr/bin/python3
class colo:
    HEADER = '\033[95m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    UNDERLINE = '\033[4m'
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'
    BOLD='\033[1;37m'
    YELLOW='\033[1;33m'

import os
import sys

if len(sys.argv) == 1:
    print(colo.RED + "Argument missing." + colo.NC)
    exit(0)

filename = sys.argv[1]
if filename.endswith('.cpp'):
    filename = filename[:-4]

if not os.path.isfile(filename + '.cpp'):
    print(colo.RED + "File " + colo.NC + '"' + filename + '"' + colo.RED + " does not exist." + colo.NC)
    exit(0)

filename = filename.upper()
print(colo.CYAN + "[GENIO: " + colo.YELLOW + filename + colo.CYAN + "]" + colo.NC)
os.system('touch %s.inp' % filename)
os.system('touch %s.out' % filename)
print(colo.GREEN + "[FINISHED]" + colo.NC)