#!/usr/bin/python3
import json
import sys
import webbrowser
import os

if(len(sys.argv) < 2):
    print('Not enough arguments')
    exit(0)

f = open('/home/hikarii/.local/bin/VOJData/links.json', 'r')
problemname = json.load(f)
f.close()

f = open('/home/hikarii/.local/bin/VOJData/contest_name.json', 'r')
contests = json.load(f)
f.close()

file = sys.argv[1].upper()
task = file
if(file.endswith('.CPP')):
    task = file[:-4]

print('Submitting for problem: %s' % task)
try:
    inp = problemname[task].split(',')
except:
    print('hey u sure the problem exists?')
    exit(0)

def loadproblem(s):
    contestid = s.split('/')[0]
    problemletter = s.split('/')[1]
    print('Loading contest %s, problem %s...' % (contests[contestid], task))
    try:
        submitlink = 'https://codeforces.com/group/FLVn1Sc504/contest/%s/problem/%s' % (contestid, problemletter)
        os.system('cf submit %s' % (submitlink))
    except:
        print('Error.')
        exit(0)
    print('Done.')

if(len(inp) == 1):
    loadproblem(inp[0])

else:
    print('There are several contests to submit this problem:')
    id = 1
    for pb in inp:
        contest = pb.split('/')[0]
        print('>>> (%d) %s' % (id, contests[contest]))
        id += 1
    option = int(input('Choose one: '))
    if 1 > option or option > len(inp):
        print('Invalid option.\nQuitting...')
        exit(0)
    else:
        loadproblem(inp[option - 1])
