#!/usr/bin/python3
class colo:
    HEADER = '\033[95m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    UNDERLINE = '\033[4m'
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'
    BOLD='\033[1;37m'
    YELLOW='\033[1;33m'

import json
import sys
import webbrowser

if(len(sys.argv) < 2):
    print('%sNot enough arguments.%s' % (colo.RED, colo.NC))
    exit(0)

f = open('/home/hikarii/.local/bin/VOJData/links.json', 'r')
problemname = json.load(f)
f.close()

f = open('/home/hikarii/.local/bin/VOJData/contest_name.json', 'r')
contests = json.load(f)
f.close()

task = sys.argv[1].upper()
if(task.endswith('.CPP')):
    task = task[:-4]
try:
    inp = problemname[task].split(',')
except:
    print('%shey u sure the problem exists?%s' % (colo.RED, colo.NC))
    exit(0)

def loadproblem(s):
    contestid = s.split('/')[0]
    problemletter = s.split('/')[1]
    print('%sLoading contest %s, problem %s...%s' % (colo.RED, contests[contestid], task, colo.NC))
    try:
        webbrowser.open('https://codeforces.com/group/FLVn1Sc504/contest/%s/problem/%s' % (contestid, problemletter))
    except:
        print('%sError.%s' % (colo.RED, colo.NC))
        exit(0)
    print('%sDone.%s' % (colo.GREEN, colo.NC))

if(len(inp) == 1):
    loadproblem(inp[0])

else:
    print('%sThere are several contests to submit this problem:%s' % (colo.YELLOW, colo.NC))
    id = 1
    for pb in inp:
        contest = pb.split('/')[0]
        print('>>> (%d) %s' % (id, contests[contest]))
        id += 1
    option = int(input('%sChoose one: %s' % (colo.YELLOW, colo.NC)))
    if 1 > option or option > len(inp):
        print('%sInvalid option.\nQuitting...%s' % (colo.RED, colo.NC))
        exit(0)
    else:
        loadproblem(inp[option - 1])

